
-- LABORATORIOS_COMPUTO

CREATE SCHEMA LABORATORIOS_COMPUTO;

--------------- TABLES ---------------

CREATE TABLE LABORATORIOS_COMPUTO.ACADEMIA(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NOMBRE TEXT NOT NULL,
  CICLO TEXT NOT NULL,
  CUATRIMESTRE TEXT NOT NULL
);

CREATE TABLE LABORATORIOS_COMPUTO.CAMPO_CLINICO(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NOMBRE TEXT NOT NULL
);


CREATE TABLE LABORATORIOS_COMPUTO.DIRECCION_CAMPO_CLINICO(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  CALLE_AVENIDA TEXT NOT NULL,
  NUMERO TEXT NOT NULL,
  COLONIA TEXT NOT NULL,
  CODIGO_POSTAL TEXT NOT NULL,
  DELEGACION_MUNICIPIO TEXT NOT NULL,
  ENTIDAD_FEDERATIVA TEXT NOT NULL,
  REFERENCIA TEXT,
  CAMPO_CLINICO_ID BIGINT NOT NULL,
  CONSTRAINT FK_CAMPO_CLINICO FOREIGN KEY (CAMPO_CLINICO_ID)
  REFERENCES LABORATORIOS_COMPUTO.CAMPO_CLINICO (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.GRUPO_PRACTICA(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NOMBRE TEXT NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  LUGARES SMALLINT NOT NULL,
  ACADEMIA_ID BIGINT NOT NULL,
  CAMPO_CLINICO_ID BIGINT NOT NULL,
  CONSTRAINT FK_ACADEMIA FOREIGN KEY (ACADEMIA_ID)
  REFERENCES LABORATORIOS_COMPUTO.ACADEMIA (ID) MATCH SIMPLE,
  CONSTRAINT FK_CAMPO_CLINICO FOREIGN KEY (CAMPO_CLINICO_ID)
  REFERENCES LABORATORIOS_COMPUTO.CAMPO_CLINICO (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.GRUPO_TEORIA(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NOMBRE TEXT NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  ACADEMIA_ID BIGINT NOT NULL,
  CONSTRAINT FK_ACADEMIA FOREIGN KEY (ACADEMIA_ID)
  REFERENCES LABORATORIOS_COMPUTO.ACADEMIA (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.HORARIO_GRUPO_PRACTICA(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  TURNO TEXT NOT NULL,
  HORA_INICIO TIME NOT NULL,
  HORA_FIN TIME NOT NULL,
  GRUPO_PRACTICA_ID BIGINT NOT NULL,
  CONSTRAINT FK_GRUPO FOREIGN KEY (GRUPO_PRACTICA_ID)
  REFERENCES LABORATORIOS_COMPUTO.GRUPO_PRACTICA (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.HORARIO_GRUPO_TEORIA(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  TURNO TEXT NOT NULL,
  HORA_INICIO TIME NOT NULL,
  HORA_FIN TIME NOT NULL,
  GRUPO_TEORIA_ID BIGINT NOT NULL,
  CONSTRAINT FK_GRUPO FOREIGN KEY (GRUPO_TEORIA_ID)
  REFERENCES LABORATORIOS_COMPUTO.GRUPO_TEORIA (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.ALUMNO(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NUMERO_CUENTA TEXT NOT NULL UNIQUE,
  NOMBRE TEXT NOT NULL,
  APELLIDOS TEXT NOT NULL,
  PROMEDIO REAL NOT NULL ,
  GRUPO_PRACTICA_ID BIGINT,
  GRUPO_TEORIA_ID BIGINT,
  CONSTRAINT FK_GRUPO_PRACTICA FOREIGN KEY (GRUPO_PRACTICA_ID)
  REFERENCES LABORATORIOS_COMPUTO.GRUPO_PRACTICA (ID) MATCH SIMPLE,
  CONSTRAINT FK_GRUPO_TEORIA FOREIGN KEY (GRUPO_TEORIA_ID)
  REFERENCES LABORATORIOS_COMPUTO.GRUPO_TEORIA (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.TELEFONO_ALUMNO(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NUMERO TEXT NOT NULL,
  TIPO TEXT NOT NULL,
  ALUMNO_ID BIGINT NOT NULL ,
  CONSTRAINT FK_ALUMNO FOREIGN KEY (ALUMNO_ID)
  REFERENCES LABORATORIOS_COMPUTO.ALUMNO (ID) MATCH SIMPLE
);

CREATE TABLE LABORATORIOS_COMPUTO.DOCUMENTO_ALUMNO(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NOMBRE TEXT NOT NULL,
  TIPO TEXT NOT NULL,
  CONTENIDO BYTEA NOT NULL,
  ALUMNO_ID BIGINT NOT NULL ,
  CONSTRAINT FK_ALUMNO FOREIGN KEY (ALUMNO_ID)
  REFERENCES LABORATORIOS_COMPUTO.ALUMNO (ID) MATCH SIMPLE

);

CREATE TABLE LABORATORIOS_COMPUTO.VACUNA(
  ID BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
  NOMBRE TEXT NOT NULL,
  ALUMNO_ID BIGINT NOT NULL ,
  CONSTRAINT FK_ALUMNO FOREIGN KEY (ALUMNO_ID)
  REFERENCES LABORATORIOS_COMPUTO.ALUMNO (ID) MATCH SIMPLE
);

--------------- INSERTS ---------------

-- ACADEMIA

INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería en salud pública','16-2','4');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Fundamentos de enfermería','16-2','5');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería quirúrgica','16-2','6');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería médico-quirúrgica','16-2','7');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería en gineco-obstericia','16-2','8');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería pediátrica','16-2','9');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería psiquiátrica','16-2','10');
INSERT INTO LABORATORIOS_COMPUTO.academia(nombre, ciclo, cuatrimestre)
VALUES ('Enfermería geriátrica','16-2','11');


/*

INSERT INTO laboratorios_computo.grupo(nombre, tipo, fecha_inicio, lugares, academia_id, campo_clinico_id)
    VALUES ('DASD','ASDAS','2016-27-02',14,1,1)


INSERT INTO laboratorios_computo.horario_grupo(
  TURNO, HORA_INICIO, HORA_FIN, GRUPO_ID)
    VALUES ('matutino','04:05:06','05:05:06',1);


DROP TABLE LABORATORIOS_COMPUTO.TELEFONO_ALUMNO;
DROP TABLE LABORATORIOS_COMPUTO.VACUNA;
DROP TABLE LABORATORIOS_COMPUTO.DOCUMENTO_ALUMNO;
DROP TABLE LABORATORIOS_COMPUTO.ALUMNO;
DROP TABLE LABORATORIOS_COMPUTO.HORARIO_GRUPO_PRACTICA;
DROP TABLE LABORATORIOS_COMPUTO.HORARIO_GRUPO_TEORIA;
DROP TABLE LABORATORIOS_COMPUTO.GRUPO_PRACTICA;
DROP TABLE LABORATORIOS_COMPUTO.GRUPO_TEORIA;
DROP TABLE LABORATORIOS_COMPUTO.DIRECCION_CAMPO_CLINICO;
DROP TABLE LABORATORIOS_COMPUTO.CAMPO_CLINICO;
DROP TABLE LABORATORIOS_COMPUTO.ACADEMIA;
*/


